[actdead] fix actdead charging animation
mer-hybris/android_system_core pull request #21
Opened 2016-12-13 22:09 UTC by kimmoli

Do not start the android charger class (which would fight on screen domination with actdead charging animation), trigger early-boot and boot.

Requires also staring of droid-hal-init.service from actdead-pre.target
(e.g. https://github.com/mer-hybris/droid-config-onyx/pull/23 )

Requires also loading of all properties
(e.g. https://github.com/mer-hybris/android_device_oneplus_onyx/pull/6 )

2016-12-15 20:52 UTC, mlehtima commented
LGTM, same fix worked on Fairphone 2.

2017-02-22 18:22 UTC, kimmoli commented
Was there some objections against this?

2018-01-27 19:48 UTC, kimmoli commented
ping

2018-01-27 19:51 UTC, sledges requested changes

2018-01-27 19:51 UTC, sledges commented on rootdir/init.rc
`trigger late-init` should trigger early-boot and boot, so hopefully a safe replacement (would be nice to test before on some community devices)

and it's also known that `late-init` brings audio up (unsure why audio is needed during actdead mode, maybe @mkosola could explain :)

Also looks like not all devices would need such changes as https://github.com/mer-hybris/android_device_oneplus_onyx/pull/6 so we might be lucky by just getting this system_core PR in

2018-01-27 19:53 UTC, sledges commented on rootdir/init.rc
See https://github.com/mer-hybris/android_system_core/commit/835ce7fcb45716ab92b0ecf73e2170ebaa448f1e

2018-01-27 20:07 UTC, mlehtima commented on rootdir/init.rc
Using trigger late-init removes the need to modify init.qcom.rc as we had done before so this should be enough for all devices. Tested on FP2.

2018-01-28 14:43 UTC, kimmoli commented
Updated

2018-01-28 16:51 UTC, sledges approved these changes

2018-01-28 16:57 UTC, sledges requested changes
> Requires also loading of all properties
> <...>

This bit no longer needed in https://github.com/mer-hybris/android_system_core/pull/21#issue-195383015

Mer Hybris patches to Android should identify themselves with `(hybris)` in the commit message. Especially prevalent starting with Android 6 (see https://github.com/mer-hybris/android_system_core/commits/hybris-13.0). This way it's easier to transfer patchsets to a new base.
It can be written as `(hybris)[actdead]` or `[actdead](hybris)` if wanting to retain tag, or even better `(hybris) actdead: ...` for kernel-style cleanliness.

2018-01-28 17:51 UTC, kimmoli commented
Commit messages fixed. Updated PR description.

2018-01-28 19:00 UTC, sledges commented
I know this is growing old, but "(hybris) actdead: fix charging animation" would be leaner and meaner :)

2018-01-28 19:14 UTC, kimmoli commented
https://www.youtube.com/watch?v=L4mP9pR-mzU ?

2018-01-28 20:09 UTC, sledges approved these changes
🥜

2018-01-28 20:10 UTC, merged

2018-01-29 07:33 UTC, mkosola commented on rootdir/init.rc
@sledges audio is needed for alarms in actdead mode.